"""Move is_admin and data_lookback_days to user_permissions

Revision ID: 0aa0df61a937
Revises: 6b50af58c536
Create Date: 2026-09-09 11:14:26.125739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa0df61a937'
down_revision: Union[str, Sequence[str], None] = '6b50af58c536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_lookback_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('data_lookback_days')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_lookback_days', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_column('data_lookback_days')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
