"""Rename call_metrics to ccf_data and add unique constraint

Revision ID: 0c0fd5f6d303
Revises: 7df4d2ca0214
Create Date: 2026-08-18 10:41:08.479357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0fd5f6d303'
down_revision: Union[str, Sequence[str], None] = '7df4d2ca0214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ccf_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('date_logged', sa.String(), nullable=True),
    sa.Column('call_timestamp', sa.String(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('call_offered', sa.Float(), nullable=True),
    sa.Column('aban_calls_10_sec', sa.Float(), nullable=True),
    sa.Column('acd_calls_10_sec', sa.Float(), nullable=True),
    sa.Column('acd_calls_20_sec', sa.Float(), nullable=True),
    sa.Column('aban_calls', sa.Float(), nullable=True),
    sa.Column('held_calls', sa.Float(), nullable=True),
    sa.Column('service_level_pct', sa.Float(), nullable=True),
    sa.Column('service_level_status', sa.String(), nullable=True),
    sa.Column('acd_calls', sa.Float(), nullable=True),
    sa.Column('hold_time', sa.Float(), nullable=True),
    sa.Column('avg_hold_time', sa.Float(), nullable=True),
    sa.Column('hold_time_status', sa.String(), nullable=True),
    sa.Column('acd_time', sa.Float(), nullable=True),
    sa.Column('acw_time', sa.Float(), nullable=True),
    sa.Column('avg_handle_time', sa.Float(), nullable=True),
    sa.Column('aht_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'language', 'call_timestamp', name='uq_ccf_data')
    )
    with op.batch_alter_table('ccf_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ccf_data_call_timestamp'), ['call_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_ccf_data_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_ccf_data_date_logged'), ['date_logged'], unique=False)
        batch_op.create_index(batch_op.f('ix_ccf_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ccf_data_language'), ['language'], unique=False)

    with op.batch_alter_table('call_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_metrics_call_timestamp'))
        batch_op.drop_index(batch_op.f('ix_call_metrics_company'))
        batch_op.drop_index(batch_op.f('ix_call_metrics_date_logged'))
        batch_op.drop_index(batch_op.f('ix_call_metrics_id'))
        batch_op.drop_index(batch_op.f('ix_call_metrics_language'))

    op.drop_table('call_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('company', sa.VARCHAR(), nullable=True),
    sa.Column('date_logged', sa.VARCHAR(), nullable=True),
    sa.Column('call_offered', sa.FLOAT(), nullable=True),
    sa.Column('aban_calls_10_sec', sa.FLOAT(), nullable=True),
    sa.Column('acd_calls_20_sec', sa.FLOAT(), nullable=True),
    sa.Column('service_level_pct', sa.FLOAT(), nullable=True),
    sa.Column('service_level_status', sa.VARCHAR(), nullable=True),
    sa.Column('acd_calls', sa.FLOAT(), nullable=True),
    sa.Column('hold_time', sa.FLOAT(), nullable=True),
    sa.Column('avg_hold_time', sa.FLOAT(), nullable=True),
    sa.Column('hold_time_status', sa.VARCHAR(), nullable=True),
    sa.Column('acd_time', sa.FLOAT(), nullable=True),
    sa.Column('acw_time', sa.FLOAT(), nullable=True),
    sa.Column('avg_handle_time', sa.FLOAT(), nullable=True),
    sa.Column('aht_status', sa.VARCHAR(), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.Column('call_timestamp', sa.VARCHAR(), nullable=True),
    sa.Column('day', sa.VARCHAR(), nullable=True),
    sa.Column('acd_calls_10_sec', sa.FLOAT(), nullable=True),
    sa.Column('aban_calls', sa.FLOAT(), nullable=True),
    sa.Column('held_calls', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_metrics_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_metrics_date_logged'), ['date_logged'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_metrics_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_metrics_call_timestamp'), ['call_timestamp'], unique=False)

    with op.batch_alter_table('ccf_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ccf_data_language'))
        batch_op.drop_index(batch_op.f('ix_ccf_data_id'))
        batch_op.drop_index(batch_op.f('ix_ccf_data_date_logged'))
        batch_op.drop_index(batch_op.f('ix_ccf_data_company'))
        batch_op.drop_index(batch_op.f('ix_ccf_data_call_timestamp'))

    op.drop_table('ccf_data')
    # ### end Alembic commands ###
