"""update_unimate_schema

Revision ID: 2ebaced5df60
Revises: cdea3ec8d228
Create Date: 2026-08-24 00:24:55.126434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ebaced5df60'
down_revision: Union[str, Sequence[str], None] = 'cdea3ec8d228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unimate_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ucid', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('day_of_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('call_start_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('call_end_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('call_duration', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ani', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dnis', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('authentication', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('auth_mechanism', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('termination_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('termination_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_unimate_data_call_timestamp'))
        batch_op.drop_index(batch_op.f('ix_unimate_data_date_logged'))
        batch_op.drop_constraint(batch_op.f('uq_unimate_data'), type_='unique')
        batch_op.create_unique_constraint('uq_unimate_data', ['ucid'])
        batch_op.create_index(batch_op.f('ix_unimate_data_call_start_time'), ['call_start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_unimate_data_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unimate_data_ucid'), ['ucid'], unique=False)
        batch_op.drop_column('aht_status')
        batch_op.drop_column('held_calls')
        batch_op.drop_column('date_logged')
        batch_op.drop_column('acd_time')
        batch_op.drop_column('acw_time')
        batch_op.drop_column('avg_hold_time')
        batch_op.drop_column('call_timestamp')
        batch_op.drop_column('aban_calls')
        batch_op.drop_column('acd_calls_10_sec')
        batch_op.drop_column('aban_calls_10_sec')
        batch_op.drop_column('hold_time')
        batch_op.drop_column('service_level_pct')
        batch_op.drop_column('call_offered')
        batch_op.drop_column('acd_calls_20_sec')
        batch_op.drop_column('acd_calls')
        batch_op.drop_column('day')
        batch_op.drop_column('hold_time_status')
        batch_op.drop_column('avg_handle_time')
        batch_op.drop_column('service_level_status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unimate_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_level_status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('avg_handle_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('hold_time_status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('day', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('acd_calls', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('acd_calls_20_sec', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('call_offered', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('service_level_pct', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('hold_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('aban_calls_10_sec', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('acd_calls_10_sec', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('aban_calls', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('call_timestamp', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('avg_hold_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('acw_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('acd_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('date_logged', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('held_calls', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('aht_status', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_unimate_data_ucid'))
        batch_op.drop_index(batch_op.f('ix_unimate_data_session_id'))
        batch_op.drop_index(batch_op.f('ix_unimate_data_call_start_time'))
        batch_op.drop_constraint('uq_unimate_data', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_unimate_data'), ['company', 'language', 'call_timestamp'])
        batch_op.create_index(batch_op.f('ix_unimate_data_date_logged'), ['date_logged'], unique=False)
        batch_op.create_index(batch_op.f('ix_unimate_data_call_timestamp'), ['call_timestamp'], unique=False)
        batch_op.drop_column('region')
        batch_op.drop_column('description')
        batch_op.drop_column('termination_reason')
        batch_op.drop_column('termination_type')
        batch_op.drop_column('auth_mechanism')
        batch_op.drop_column('authentication')
        batch_op.drop_column('dnis')
        batch_op.drop_column('ani')
        batch_op.drop_column('call_duration')
        batch_op.drop_column('call_end_time')
        batch_op.drop_column('call_start_time')
        batch_op.drop_column('day_of_week')
        batch_op.drop_column('session_id')
        batch_op.drop_column('ucid')

    # ### end Alembic commands ###
