"""Update AgentMetadata

Revision ID: 62a625ae6135
Revises: cafbd7568b87
Create Date: 2026-08-31 12:37:04.730708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a625ae6135'
down_revision: Union[str, Sequence[str], None] = 'cafbd7568b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('total_acd_calls', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_staffed_time_sec', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_acd_time_sec', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_acw_time_sec', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_occupancy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('composite_score', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agent_metadata_company'), ['company'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_metadata_company'))
        batch_op.drop_column('composite_score')
        batch_op.drop_column('avg_occupancy')
        batch_op.drop_column('total_acw_time_sec')
        batch_op.drop_column('total_acd_time_sec')
        batch_op.drop_column('total_staffed_time_sec')
        batch_op.drop_column('total_acd_calls')
        batch_op.drop_column('language')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
