"""Add companies JSON

Revision ID: 6672aca0fe2e
Revises: 
Create Date: 2026-08-11 14:40:31.767004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6672aca0fe2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companies', sa.JSON(), nullable=True))
        
    op.execute("UPDATE users SET companies = json_array(company_name)")
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('companies')

    # ### end Alembic commands ###
