"""explicit boolean permissions

Revision ID: 6b50af58c536
Revises: a002bf32259b
Create Date: 2026-09-09 10:54:01.019571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6b50af58c536'
down_revision: Union[str, Sequence[str], None] = 'a002bf32259b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_digitech', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('company_nsb', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_ccf', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_unimate', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_cdr', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_apr', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_download_files', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_user_permissions_user_id', ['user_id'])
        batch_op.drop_column('permission_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('companies')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companies', sqlite.JSON(), nullable=True))
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('uq_user_permissions_user_id', type_='unique')
        batch_op.drop_column('can_download_files')
        batch_op.drop_column('can_view_apr')
        batch_op.drop_column('can_view_cdr')
        batch_op.drop_column('can_view_unimate')
        batch_op.drop_column('can_view_ccf')
        batch_op.drop_column('company_nsb')
        batch_op.drop_column('company_digitech')

    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
