"""Add user_agent and endpoint to AuditLog

Revision ID: 7df4d2ca0214
Revises: dcbf1a1eee6c
Create Date: 2026-08-17 11:29:39.103356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df4d2ca0214'
down_revision: Union[str, Sequence[str], None] = 'dcbf1a1eee6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
