"""Initial schema

Revision ID: 857b0547559a
Revises: 
Create Date: 2026-08-12 17:25:21.375592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857b0547559a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('file_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.String(), nullable=True),
    sa.Column('uploader', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_metadata_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_metadata_id'), ['id'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('companies', sa.JSON(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('call_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('date_logged', sa.String(), nullable=True),
    sa.Column('call_timestamp', sa.String(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('call_offered', sa.Float(), nullable=True),
    sa.Column('aban_calls_10_sec', sa.Float(), nullable=True),
    sa.Column('acd_calls_10_sec', sa.Float(), nullable=True),
    sa.Column('acd_calls_20_sec', sa.Float(), nullable=True),
    sa.Column('aban_calls', sa.Float(), nullable=True),
    sa.Column('held_calls', sa.Float(), nullable=True),
    sa.Column('service_level_pct', sa.Float(), nullable=True),
    sa.Column('service_level_status', sa.String(), nullable=True),
    sa.Column('acd_calls', sa.Float(), nullable=True),
    sa.Column('hold_time', sa.Float(), nullable=True),
    sa.Column('avg_hold_time', sa.Float(), nullable=True),
    sa.Column('hold_time_status', sa.String(), nullable=True),
    sa.Column('acd_time', sa.Float(), nullable=True),
    sa.Column('acw_time', sa.Float(), nullable=True),
    sa.Column('avg_handle_time', sa.Float(), nullable=True),
    sa.Column('aht_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_metrics_call_timestamp'), ['call_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_metrics_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_metrics_date_logged'), ['date_logged'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_metrics_language'), ['language'], unique=False)

    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_permissions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permissions_id'))

    op.drop_table('user_permissions')
    with op.batch_alter_table('call_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_metrics_language'))
        batch_op.drop_index(batch_op.f('ix_call_metrics_id'))
        batch_op.drop_index(batch_op.f('ix_call_metrics_date_logged'))
        batch_op.drop_index(batch_op.f('ix_call_metrics_company'))
        batch_op.drop_index(batch_op.f('ix_call_metrics_call_timestamp'))

    op.drop_table('call_metrics')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_metadata_id'))
        batch_op.drop_index(batch_op.f('ix_file_metadata_filename'))

    op.drop_table('file_metadata')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
