"""add_cdr_data

Revision ID: b2080d685eeb
Revises: 2ebaced5df60
Create Date: 2026-08-24 17:51:12.736098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2080d685eeb'
down_revision: Union[str, Sequence[str], None] = '2ebaced5df60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cdr_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=True),
    sa.Column('acwtime', sa.Integer(), nullable=True),
    sa.Column('ansholdtime', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('segstart', sa.String(), nullable=True),
    sa.Column('segstartutc', sa.String(), nullable=True),
    sa.Column('segstop', sa.String(), nullable=True),
    sa.Column('segstoputc', sa.String(), nullable=True),
    sa.Column('talktime', sa.Integer(), nullable=True),
    sa.Column('split1', sa.String(), nullable=True),
    sa.Column('transferred', sa.Integer(), nullable=True),
    sa.Column('agt_released', sa.Integer(), nullable=True),
    sa.Column('origlogin', sa.String(), nullable=True),
    sa.Column('anslogin', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', name='uq_cdr_data')
    )
    with op.batch_alter_table('cdr_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cdr_data_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cdr_data_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_cdr_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cdr_data_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_cdr_data_segstart'), ['segstart'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cdr_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cdr_data_segstart'))
        batch_op.drop_index(batch_op.f('ix_cdr_data_language'))
        batch_op.drop_index(batch_op.f('ix_cdr_data_id'))
        batch_op.drop_index(batch_op.f('ix_cdr_data_company'))
        batch_op.drop_index(batch_op.f('ix_cdr_data_call_id'))

    op.drop_table('cdr_data')
    # ### end Alembic commands ###
