"""Remove dead KPI columns from CCFData

Revision ID: b6341695e81a
Revises: fab9096a648e
Create Date: 2026-08-28 15:11:53.480782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6341695e81a'
down_revision: Union[str, Sequence[str], None] = 'fab9096a648e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ccf_data', schema=None) as batch_op:
        batch_op.drop_column('service_level_status')
        batch_op.drop_column('service_level_pct')
        batch_op.drop_column('aht_status')
        batch_op.drop_column('avg_handle_time')
        batch_op.drop_column('avg_hold_time')
        batch_op.drop_column('hold_time_status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ccf_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hold_time_status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('avg_hold_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('avg_handle_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('aht_status', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('service_level_pct', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('service_level_status', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
