"""Add UniMateData

Revision ID: cdea3ec8d228
Revises: 4e761ad3ebbd
Create Date: 2026-08-24 00:15:37.344759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdea3ec8d228'
down_revision: Union[str, Sequence[str], None] = '4e761ad3ebbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unimate_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('date_logged', sa.String(), nullable=True),
    sa.Column('call_timestamp', sa.String(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('call_offered', sa.Float(), nullable=True),
    sa.Column('aban_calls_10_sec', sa.Float(), nullable=True),
    sa.Column('acd_calls_10_sec', sa.Float(), nullable=True),
    sa.Column('acd_calls_20_sec', sa.Float(), nullable=True),
    sa.Column('aban_calls', sa.Float(), nullable=True),
    sa.Column('held_calls', sa.Float(), nullable=True),
    sa.Column('service_level_pct', sa.Float(), nullable=True),
    sa.Column('service_level_status', sa.String(), nullable=True),
    sa.Column('acd_calls', sa.Float(), nullable=True),
    sa.Column('hold_time', sa.Float(), nullable=True),
    sa.Column('avg_hold_time', sa.Float(), nullable=True),
    sa.Column('hold_time_status', sa.String(), nullable=True),
    sa.Column('acd_time', sa.Float(), nullable=True),
    sa.Column('acw_time', sa.Float(), nullable=True),
    sa.Column('avg_handle_time', sa.Float(), nullable=True),
    sa.Column('aht_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company', 'language', 'call_timestamp', name='uq_unimate_data')
    )
    with op.batch_alter_table('unimate_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unimate_data_call_timestamp'), ['call_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_unimate_data_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_unimate_data_date_logged'), ['date_logged'], unique=False)
        batch_op.create_index(batch_op.f('ix_unimate_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unimate_data_language'), ['language'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unimate_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unimate_data_language'))
        batch_op.drop_index(batch_op.f('ix_unimate_data_id'))
        batch_op.drop_index(batch_op.f('ix_unimate_data_date_logged'))
        batch_op.drop_index(batch_op.f('ix_unimate_data_company'))
        batch_op.drop_index(batch_op.f('ix_unimate_data_call_timestamp'))

    op.drop_table('unimate_data')
    # ### end Alembic commands ###
