"""add is_fcr to unimate_data

Revision ID: d2c12956e32c
Revises: b2080d685eeb
Create Date: 2026-08-27 11:29:27.627555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c12956e32c'
down_revision: Union[str, Sequence[str], None] = 'b2080d685eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anslogin', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_metadata_anslogin'), ['anslogin'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_metadata_id'), ['id'], unique=False)

    op.create_table('customer_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ani', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('last_contact_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_metadata_ani'), ['ani'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_metadata_id'), ['id'], unique=False)

    op.create_table('disposition_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('termination_reason', sa.String(), nullable=False),
    sa.Column('disposition_category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disposition_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disposition_metadata_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disposition_metadata_termination_reason'), ['termination_reason'], unique=True)

    with op.batch_alter_table('unimate_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fcr', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unimate_data', schema=None) as batch_op:
        batch_op.drop_column('is_fcr')

    with op.batch_alter_table('disposition_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disposition_metadata_termination_reason'))
        batch_op.drop_index(batch_op.f('ix_disposition_metadata_id'))

    op.drop_table('disposition_metadata')
    with op.batch_alter_table('customer_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_metadata_id'))
        batch_op.drop_index(batch_op.f('ix_customer_metadata_ani'))

    op.drop_table('customer_metadata')
    with op.batch_alter_table('agent_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_metadata_id'))
        batch_op.drop_index(batch_op.f('ix_agent_metadata_anslogin'))

    op.drop_table('agent_metadata')
    # ### end Alembic commands ###
