"""auto

Revision ID: faa03b3cdd78
Revises: d808b5d0c43f
Create Date: 2026-08-28 11:39:32.289609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa03b3cdd78'
down_revision: Union[str, Sequence[str], None] = 'd808b5d0c43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anslogin', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_metadata_anslogin'), ['anslogin'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_metadata_id'), ['id'], unique=False)

    op.create_table('customer_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ani', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('last_contact_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_metadata_ani'), ['ani'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_metadata_id'), ['id'], unique=False)

    op.create_table('disposition_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('termination_reason', sa.String(), nullable=False),
    sa.Column('disposition_category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disposition_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disposition_metadata_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disposition_metadata_termination_reason'), ['termination_reason'], unique=True)

    op.create_table('apr_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('date_logged', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('login_id', sa.String(), nullable=True),
    sa.Column('acd_calls', sa.Integer(), nullable=True),
    sa.Column('avg_acd_time', sa.Integer(), nullable=True),
    sa.Column('avg_acw_time', sa.Integer(), nullable=True),
    sa.Column('occupancy_with_acw', sa.Float(), nullable=True),
    sa.Column('occupancy_without_acw', sa.Float(), nullable=True),
    sa.Column('acd_time', sa.String(), nullable=True),
    sa.Column('acw_time', sa.String(), nullable=True),
    sa.Column('agent_ring_time', sa.String(), nullable=True),
    sa.Column('other_time', sa.String(), nullable=True),
    sa.Column('aux_time', sa.String(), nullable=True),
    sa.Column('avail_time', sa.String(), nullable=True),
    sa.Column('staffed_time', sa.String(), nullable=True),
    sa.Column('held_calls', sa.String(), nullable=True),
    sa.Column('tea_break', sa.String(), nullable=True),
    sa.Column('lunch_dinner', sa.String(), nullable=True),
    sa.Column('quality_feedback', sa.String(), nullable=True),
    sa.Column('email_support', sa.String(), nullable=True),
    sa.Column('briefing', sa.String(), nullable=True),
    sa.Column('system_down', sa.String(), nullable=True),
    sa.Column('meeting', sa.String(), nullable=True),
    sa.Column('trans_out', sa.Integer(), nullable=True),
    sa.Column('split_skill', sa.String(), nullable=True),
    sa.Column('conf', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_logged', 'login_id', name='uq_apr_date_login')
    )
    with op.batch_alter_table('apr_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apr_data_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_apr_data_date_logged'), ['date_logged'], unique=False)
        batch_op.create_index(batch_op.f('ix_apr_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apr_data_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_apr_data_login_id'), ['login_id'], unique=False)

    op.create_table('cdr_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=True),
    sa.Column('acwtime', sa.Integer(), nullable=True),
    sa.Column('ansholdtime', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('segstart', sa.String(), nullable=True),
    sa.Column('segstartutc', sa.String(), nullable=True),
    sa.Column('segstop', sa.String(), nullable=True),
    sa.Column('segstoputc', sa.String(), nullable=True),
    sa.Column('talktime', sa.Integer(), nullable=True),
    sa.Column('split1', sa.String(), nullable=True),
    sa.Column('transferred', sa.Integer(), nullable=True),
    sa.Column('agt_released', sa.Integer(), nullable=True),
    sa.Column('origlogin', sa.String(), nullable=True),
    sa.Column('anslogin', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', name='uq_cdr_data')
    )
    with op.batch_alter_table('cdr_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cdr_data_call_id'), ['call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cdr_data_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_cdr_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cdr_data_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_cdr_data_segstart'), ['segstart'], unique=False)

    with op.batch_alter_table('unimate_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fcr', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unimate_data', schema=None) as batch_op:
        batch_op.drop_column('is_fcr')

    with op.batch_alter_table('cdr_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cdr_data_segstart'))
        batch_op.drop_index(batch_op.f('ix_cdr_data_language'))
        batch_op.drop_index(batch_op.f('ix_cdr_data_id'))
        batch_op.drop_index(batch_op.f('ix_cdr_data_company'))
        batch_op.drop_index(batch_op.f('ix_cdr_data_call_id'))

    op.drop_table('cdr_data')
    with op.batch_alter_table('apr_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apr_data_login_id'))
        batch_op.drop_index(batch_op.f('ix_apr_data_language'))
        batch_op.drop_index(batch_op.f('ix_apr_data_id'))
        batch_op.drop_index(batch_op.f('ix_apr_data_date_logged'))
        batch_op.drop_index(batch_op.f('ix_apr_data_company'))

    op.drop_table('apr_data')
    with op.batch_alter_table('disposition_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disposition_metadata_termination_reason'))
        batch_op.drop_index(batch_op.f('ix_disposition_metadata_id'))

    op.drop_table('disposition_metadata')
    with op.batch_alter_table('customer_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_metadata_id'))
        batch_op.drop_index(batch_op.f('ix_customer_metadata_ani'))

    op.drop_table('customer_metadata')
    with op.batch_alter_table('agent_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_metadata_id'))
        batch_op.drop_index(batch_op.f('ix_agent_metadata_anslogin'))

    op.drop_table('agent_metadata')
    # ### end Alembic commands ###
